export enum AgentLifecycleState {
  INITIALIZING = 'INITIALIZING',
  STARTING = 'STARTING',
  RUNNING = 'RUNNING',
  DEGRADED = 'DEGRADED',
  OFFLINE = 'OFFLINE',
  RECOVERING = 'RECOVERING',
  STOPPING = 'STOPPING',
  STOPPED = 'STOPPED',
  STOPPED_FOR_SAFETY = 'STOPPED_FOR_SAFETY',
  FAILED = 'FAILED'
}

export enum EngineProcessState {
  STOPPED = 'STOPPED',
  STARTING = 'STARTING',
  RUNNING = 'RUNNING',
  CRASHED = 'CRASHED',
  RECOVERING = 'RECOVERING',
  STOPPED_FOR_SAFETY = 'STOPPED_FOR_SAFETY'
}

export enum HealthStatus {
  HEALTHY = 'HEALTHY',
  DEGRADED = 'DEGRADED',
  UNHEALTHY = 'UNHEALTHY',
  OFFLINE = 'OFFLINE',
  RECOVERING = 'RECOVERING'
}
